language: minimal
install: skip

services: docker

before_install: docker pull verilator/verilator:latest

script:
        # Unset the VERILATOR variable so the container won't fail when running inside another container in Travis
        docker run --rm -t -v `pwd`:/build -w /build --entrypoint /bin/bash verilator/verilator:latest -c "apt update && apt install -y default-jre-headless python3-pexpect curl && make VERILATOR= check"
